{
 "title": "FoodExpress Realtime Overview",
 "tags": [
  "ecommerce",
  "foodexpress"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Orders",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT SUM(total_orders) FROM realtime_order_metrics;"
    }
   ]
  },
  {
   "title": "Total Revenue ($)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT SUM(total_revenue) FROM realtime_order_metrics;"
    }
   ]
  },
  {
   "title": "Orders Dynamic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT window_end AS time, total_orders FROM realtime_order_metrics WHERE $__timeFilter(window_end) ORDER BY time;"
    }
   ]
  },
  {
   "title": "Top Restaurants by Orders",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT SUM(total_revenue) FROM realtime_order_metrics;"
    }
   ]
  }
 ]
}